### ISSUE TITLE
I can't understand how we can transform all handlebars files to jsx templates

### ISSUE THREAD

**Issue by Aleksandyr** [Gerrit0/typedoc-custom-theme-demo#1]
Can you please make this theme closer to what the default theme should look like?

**Comment by Aleksandyr** [comment]
@Gerrit0 please give more documentation for converting a custom theme to functional JSX template theme

**Comment by Gerrit0** [comment]
TypeDoc supports partial patching of theme partials - you generally aren't supposed to replace every template since then your theme won't benefit from any fixes introduced in TypeDoc.

https://github.com/TypeStrong/typedoc/tree/master/src/lib/output/themes/default/partials contains (for the most part, somewhat refactored) the JSX equivalent as the original handlebars.

**Comment by Aleksandyr** [comment]
@Gerrit0 thanks for sending that.
I see that my CSS is not included in the static site at the end, my `assets` folder is not the one I ship with my custom theme which is an npm package.  
 
 What I am doing is I am having the same structure as the old default theme. Some of the partial templates, default layouts, and the index have been transferred to the `jsx template` as it was suggested. 

In my `default` **layout** I am generating my main.css which is in the `assets` folder but the problem here is that my `assets` folder is not generated as it is in the package that is installed. It is getting the default structure of it which leads to missing my main.css file.

**Comment by Aleksandyr** [comment]
I thought that once we have a custom theme(which is an npm package) that has a load method with **typedoc-theme** as a keyword we can set it through the `--theme` option by passing the name of the registered theme e.g `customTheme`:
**typedoc --theme customTheme**

It turned out that this way was not including the styles I have defined in the `assets ` folder. I made it work by passing the path to the **dist** folder of my theme:
`typedoc --theme node_modules/customTheme/dist`

Is this the right way for passing a reference to a custom theme?
Because I read in the API doc that you can only pass the name of the theme that gets registered by the library itself. But that is not how the styles get integrated into the build

**Comment by Aleksandyr** [comment]
I have managed to pass my custom styles through `--customCss` option and now I am trying to figure out how I can include all my custom js scripts into the main.js folder or how I can transfer them into the assets folder that is generated by typedoc.

**Comment by Gerrit0** [comment]
For custom themes, I'd recommend adding a listener to `app.renderer.on(RendererEvent.END`, which will receive a `RendererEvent`, you can then copy data to `event.outputDirectory` after checking that the `app.renderer.theme instanceof YourTheme`
